### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by krixstin** [krixstin/ssw345-hw3#1]
@krixstin 
- [x] edit README.md
- [x] upload a screenshot of completed assignments
- [x] submit repo to canvas assignment
